# Generated by Django 2.1.2 on 2018-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='read_only_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
