# Generated by Django 2.1.2 on 2018-10-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_read_only_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Campaign')),
            ],
        ),
    ]
